Repository observingClouds/xbitinfo, pull requests merged in 2022-05, with the labels that each got.

#89 fix rtd
  .readthedocs.yaml
  docs/environment.yml
Labels: infrastructure

#85 Reduce dependencies
  README.md
  docs/index.rst
  requirements.txt
  setup.py
  xbitinfo/bitround.py
  xbitinfo/graphics.py
  xbitinfo/save_compressed.py
Labels: dependencies

#86 typos
  docs/environment.yml
  environment.yml
  setup.py
  xbitinfo/bitround.py
  xbitinfo/graphics.py
  xbitinfo/save_compressed.py
  xbitinfo/xbitinfo.py
Labels: cleanup

#91 add pre/post pytest hooks for clean tmp dir handling
  conftest.py
  tests/test_bitinformation_pipeline.py
  tests/test_get_bitinformation.py
  tests/test_save_compressed.py
Labels: testing

#93 get BitInformation.jl version and include in info_per_bits
  xbitinfo/xbitinfo.py
Labels: enhancement

#94 continuing fix_sphinx
  .github/workflows/ci.yaml
  .readthedocs.yaml
  AUTHORS.rst
  CHANGELOG.rst
  MANIFEST.in
  README.md
  docs/conf.py
  docs/environment.yml
  docs/index.rst
  docs/quick-start.ipynb
  environment.yml
  setup.py
  xbitinfo/bitround.py
  xbitinfo/graphics.py
  xbitinfo/save_compressed.py
  xbitinfo/xbitinfo.py
Labels: documentation

#96 reduce dependencies followup
  requirements.txt
Labels: dependencies, cleanup

#101 fix kwargs reused
  CHANGELOG.rst
  docs/conf.py
  tests/test_get_bitinformation.py
  xbitinfo/xbitinfo.py
Labels: bug

#100 refactor `xb.get_keepbits` with `xarray`
  CHANGELOG.rst
  tests/test_get_keepbits.py
  xbitinfo/xbitinfo.py
Labels: refactor

#106 allow `get_bitinformation(dim)` as `list`
  CHANGELOG.rst
  tests/test_get_bitinformation.py
  xbitinfo/xbitinfo.py
Labels: enhancement
