Repository observingClouds/xbitinfo, pull requests merged in 2022-04, with the labels that each got.

#13 notebooks under CI
  .github/workflows/ci.yaml
  examples/quick-start.ipynb
  examples/singe_file_example.ipynb
Labels: documentation, enhancement, infrastructure

#20 bitinformation(kwargs)
  bitinformation_pipeline/bitinformation_pipeline.py
  bitinformation_pipeline/get_n_plot_bitinformation.jl
  examples/quick-start.ipynb
  tests/test_bitinformation_pipeline.py
  tests/test_get_bitinformation.py
Labels: enhancement

#18 instructions `levante.dkrz.de`
  setup_levante.md
Labels: documentation

#21 save compressed netcdf
  .github/workflows/ci.yaml
  bitinformation_pipeline/__init__.py
  bitinformation_pipeline/bitinformation_pipeline.py
  bitinformation_pipeline/bitround.py
  bitinformation_pipeline/save_compressed.py
  conftest.py
  examples/quick-start.ipynb
  requirements.txt
  setup.py
  tests/test_bitinformation_pipeline.py
  tests/test_save_compressed.py
  tests/test_xr_bitround.py
Labels: enhancement

#26 Modify plot_bitinformation
  bitinformation_pipeline/bitinformation_pipeline.py
Labels: enhancement

#32 Fix `get_bitinformation(label)`
  bitinformation_pipeline/bitinformation_pipeline.py
  tests/test_get_bitinformation.py
Labels: bug

#29 `bp.jl_bitround`
  bitinformation_pipeline/__init__.py
  bitinformation_pipeline/bitinformation_pipeline.py
  bitinformation_pipeline/bitround.py
  examples/quick-start.ipynb
  tests/test_bitinformation_pipeline.py
  tests/test_bitround.py
  tests/test_xr_bitround.py
Labels: enhancement

#33 fix `to_compressed_netcdf` when `coords` are chunked
  bitinformation_pipeline/save_compressed.py
  tests/test_save_compressed.py
Labels: bug

#41 fix `to_compressed_netcdf` if `time_dim` not in variable
  bitinformation_pipeline/save_compressed.py
  tests/test_save_compressed.py
Labels: bug

#40 `dim` as `str` and `axis` as `int`
  bitinformation_pipeline/bitinformation_pipeline.py
  tests/test_get_bitinformation.py
Labels: enhancement

#48 benchmarking with `asv`
  .github/workflows/benchmarks.yml
  .gitignore
  CHANGELOG.rst
  CONTRIBUTING.rst
  asv_bench/asv.conf.json
  asv_bench/benchmarks/README_CI.md
  asv_bench/benchmarks/__init__.py
  asv_bench/benchmarks/benchmarks_bitround.py
  asv_bench/benchmarks/benchmarks_get_bitinformation.py
  asv_bench/benchmarks/benchmarks_get_keepbits.py
  environment.yml
  setup.py
Labels: infrastructure, performance, run-benchmark

#65 Delete ci-pre-commit.yml
  .github/workflows/ci-pre-commit.yml
Labels: cleanup

#62 Update README.md
  README.md
Labels: documentation

#72 `get_keepbits(inflevel=1.)` return max keepbits
  bitinformation_pipeline/bitinformation_pipeline.py
Labels: bug

#68 Prefect pipeline
  bitinformation_pipeline/__init__.py
  bitinformation_pipeline/bitinformation_pipeline.py
  environment.yml
  requirements.txt
  tests/test_bitinformation_pipeline.py
Labels: enhancement

#59 add `plot_distribution`
  bitinformation_pipeline/__init__.py
  bitinformation_pipeline/bitinformation_pipeline.py
  bitinformation_pipeline/graphics.py
  examples/quick-start.ipynb
Labels: enhancement

#23 Update setup_levante.md
  setup_levante.md
Labels: documentation

#73 add `bitround_along_dim` for Fig3
  bitinformation_pipeline/bitround.py
  bitinformation_pipeline/graphics.py
Labels: enhancement

#82 support `get_bitinformation(masked_value=None)`
  tests/test_get_bitinformation.py
  xbitinfo/xbitinfo.py
Labels: enhancement

#79 `info_per_bit` as `xr.Dataset`
  tests/test_get_bitinformation.py
  xbitinfo/__init__.py
  xbitinfo/_version.py
  xbitinfo/bitround.py
  xbitinfo/xbitinfo.py
Labels: enhancement
