Repository observingClouds/xbitinfo, pull requests merged in 2022-10, with the labels that each got.

#137 sagemaker badge
  README.md
  docs/index.rst
Labels: documentation

#148 extras_require in setup.py
  .github/workflows/ci.yaml
  setup.py
Labels: infrastructure

#126 Pythonic bitinformation
  requirements.txt
  tests/test_get_bitinformation.py
  xbitinfo/_py_bitinfo.py
  xbitinfo/xbitinfo.py
Labels: enhancement, performance
